(cl:defpackage heron_srvs-srv
  (:use )
  (:export
   "ASKMODEL"
   "<ASKMODEL-REQUEST>"
   "ASKMODEL-REQUEST"
   "<ASKMODEL-RESPONSE>"
   "ASKMODEL-RESPONSE"
   "DWAMISSION"
   "<DWAMISSION-REQUEST>"
   "DWAMISSION-REQUEST"
   "<DWAMISSION-RESPONSE>"
   "DWAMISSION-RESPONSE"
   "GPSMISSION"
   "<GPSMISSION-REQUEST>"
   "GPSMISSION-REQUEST"
   "<GPSMISSION-RESPONSE>"
   "GPSMISSION-RESPONSE"
  ))

