// Generated by gencpp from file heron_srvs/AskModel.msg
// DO NOT EDIT!


#ifndef HERON_SRVS_MESSAGE_ASKMODEL_H
#define HERON_SRVS_MESSAGE_ASKMODEL_H

#include <ros/service_traits.h>


#include <heron_srvs/AskModelRequest.h>
#include <heron_srvs/AskModelResponse.h>


namespace heron_srvs
{

struct AskModel
{

typedef AskModelRequest Request;
typedef AskModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AskModel
} // namespace heron_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::heron_srvs::AskModel > {
  static const char* value()
  {
    return "83bea2f2ad45b48dc9b07a242180ea66";
  }

  static const char* value(const ::heron_srvs::AskModel&) { return value(); }
};

template<>
struct DataType< ::heron_srvs::AskModel > {
  static const char* value()
  {
    return "heron_srvs/AskModel";
  }

  static const char* value(const ::heron_srvs::AskModel&) { return value(); }
};


// service_traits::MD5Sum< ::heron_srvs::AskModelRequest> should match
// service_traits::MD5Sum< ::heron_srvs::AskModel >
template<>
struct MD5Sum< ::heron_srvs::AskModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::AskModel >::value();
  }
  static const char* value(const ::heron_srvs::AskModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::AskModelRequest> should match
// service_traits::DataType< ::heron_srvs::AskModel >
template<>
struct DataType< ::heron_srvs::AskModelRequest>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::AskModel >::value();
  }
  static const char* value(const ::heron_srvs::AskModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::heron_srvs::AskModelResponse> should match
// service_traits::MD5Sum< ::heron_srvs::AskModel >
template<>
struct MD5Sum< ::heron_srvs::AskModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::AskModel >::value();
  }
  static const char* value(const ::heron_srvs::AskModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::AskModelResponse> should match
// service_traits::DataType< ::heron_srvs::AskModel >
template<>
struct DataType< ::heron_srvs::AskModelResponse>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::AskModel >::value();
  }
  static const char* value(const ::heron_srvs::AskModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERON_SRVS_MESSAGE_ASKMODEL_H
