// Generated by gencpp from file heron_srvs/DwaMissionResponse.msg
// DO NOT EDIT!


#ifndef HERON_SRVS_MESSAGE_DWAMISSIONRESPONSE_H
#define HERON_SRVS_MESSAGE_DWAMISSIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heron_srvs
{
template <class ContainerAllocator>
struct DwaMissionResponse_
{
  typedef DwaMissionResponse_<ContainerAllocator> Type;

  DwaMissionResponse_()
    : success(false)
    , message()  {
    }
  DwaMissionResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DwaMissionResponse_

typedef ::heron_srvs::DwaMissionResponse_<std::allocator<void> > DwaMissionResponse;

typedef boost::shared_ptr< ::heron_srvs::DwaMissionResponse > DwaMissionResponsePtr;
typedef boost::shared_ptr< ::heron_srvs::DwaMissionResponse const> DwaMissionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron_srvs::DwaMissionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heron_srvs::DwaMissionResponse_<ContainerAllocator1> & lhs, const ::heron_srvs::DwaMissionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heron_srvs::DwaMissionResponse_<ContainerAllocator1> & lhs, const ::heron_srvs::DwaMissionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heron_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::heron_srvs::DwaMissionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron_srvs/DwaMissionResponse";
  }

  static const char* value(const ::heron_srvs::DwaMissionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::heron_srvs::DwaMissionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DwaMissionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron_srvs::DwaMissionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron_srvs::DwaMissionResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_SRVS_MESSAGE_DWAMISSIONRESPONSE_H
