// Generated by gencpp from file heron_srvs/DwaMissionRequest.msg
// DO NOT EDIT!


#ifndef HERON_SRVS_MESSAGE_DWAMISSIONREQUEST_H
#define HERON_SRVS_MESSAGE_DWAMISSIONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heron_srvs
{
template <class ContainerAllocator>
struct DwaMissionRequest_
{
  typedef DwaMissionRequest_<ContainerAllocator> Type;

  DwaMissionRequest_()
    : goal_x(0.0)
    , goal_y(0.0)  {
    }
  DwaMissionRequest_(const ContainerAllocator& _alloc)
    : goal_x(0.0)
    , goal_y(0.0)  {
  (void)_alloc;
    }



   typedef float _goal_x_type;
  _goal_x_type goal_x;

   typedef float _goal_y_type;
  _goal_y_type goal_y;





  typedef boost::shared_ptr< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DwaMissionRequest_

typedef ::heron_srvs::DwaMissionRequest_<std::allocator<void> > DwaMissionRequest;

typedef boost::shared_ptr< ::heron_srvs::DwaMissionRequest > DwaMissionRequestPtr;
typedef boost::shared_ptr< ::heron_srvs::DwaMissionRequest const> DwaMissionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heron_srvs::DwaMissionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heron_srvs::DwaMissionRequest_<ContainerAllocator1> & lhs, const ::heron_srvs::DwaMissionRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal_x == rhs.goal_x &&
    lhs.goal_y == rhs.goal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heron_srvs::DwaMissionRequest_<ContainerAllocator1> & lhs, const ::heron_srvs::DwaMissionRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heron_srvs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9aa8c2e2b21fc8544d27640eeac21d97";
  }

  static const char* value(const ::heron_srvs::DwaMissionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9aa8c2e2b21fc854ULL;
  static const uint64_t static_value2 = 0x4d27640eeac21d97ULL;
};

template<class ContainerAllocator>
struct DataType< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heron_srvs/DwaMissionRequest";
  }

  static const char* value(const ::heron_srvs::DwaMissionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 goal_x\n"
"float32 goal_y\n"
;
  }

  static const char* value(const ::heron_srvs::DwaMissionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_x);
      stream.next(m.goal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DwaMissionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heron_srvs::DwaMissionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heron_srvs::DwaMissionRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_x: ";
    Printer<float>::stream(s, indent + "  ", v.goal_x);
    s << indent << "goal_y: ";
    Printer<float>::stream(s, indent + "  ", v.goal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERON_SRVS_MESSAGE_DWAMISSIONREQUEST_H
