// Generated by gencpp from file heron_srvs/DwaMission.msg
// DO NOT EDIT!


#ifndef HERON_SRVS_MESSAGE_DWAMISSION_H
#define HERON_SRVS_MESSAGE_DWAMISSION_H

#include <ros/service_traits.h>


#include <heron_srvs/DwaMissionRequest.h>
#include <heron_srvs/DwaMissionResponse.h>


namespace heron_srvs
{

struct DwaMission
{

typedef DwaMissionRequest Request;
typedef DwaMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DwaMission
} // namespace heron_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::heron_srvs::DwaMission > {
  static const char* value()
  {
    return "d4f8fbf2f34a6f33bd852a1c941167c4";
  }

  static const char* value(const ::heron_srvs::DwaMission&) { return value(); }
};

template<>
struct DataType< ::heron_srvs::DwaMission > {
  static const char* value()
  {
    return "heron_srvs/DwaMission";
  }

  static const char* value(const ::heron_srvs::DwaMission&) { return value(); }
};


// service_traits::MD5Sum< ::heron_srvs::DwaMissionRequest> should match
// service_traits::MD5Sum< ::heron_srvs::DwaMission >
template<>
struct MD5Sum< ::heron_srvs::DwaMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::DwaMission >::value();
  }
  static const char* value(const ::heron_srvs::DwaMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::DwaMissionRequest> should match
// service_traits::DataType< ::heron_srvs::DwaMission >
template<>
struct DataType< ::heron_srvs::DwaMissionRequest>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::DwaMission >::value();
  }
  static const char* value(const ::heron_srvs::DwaMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::heron_srvs::DwaMissionResponse> should match
// service_traits::MD5Sum< ::heron_srvs::DwaMission >
template<>
struct MD5Sum< ::heron_srvs::DwaMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::DwaMission >::value();
  }
  static const char* value(const ::heron_srvs::DwaMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::DwaMissionResponse> should match
// service_traits::DataType< ::heron_srvs::DwaMission >
template<>
struct DataType< ::heron_srvs::DwaMissionResponse>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::DwaMission >::value();
  }
  static const char* value(const ::heron_srvs::DwaMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERON_SRVS_MESSAGE_DWAMISSION_H
