// Generated by gencpp from file heron_srvs/GpsMission.msg
// DO NOT EDIT!


#ifndef HERON_SRVS_MESSAGE_GPSMISSION_H
#define HERON_SRVS_MESSAGE_GPSMISSION_H

#include <ros/service_traits.h>


#include <heron_srvs/GpsMissionRequest.h>
#include <heron_srvs/GpsMissionResponse.h>


namespace heron_srvs
{

struct GpsMission
{

typedef GpsMissionRequest Request;
typedef GpsMissionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsMission
} // namespace heron_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::heron_srvs::GpsMission > {
  static const char* value()
  {
    return "48a816069f77785b03ce1850b9079d52";
  }

  static const char* value(const ::heron_srvs::GpsMission&) { return value(); }
};

template<>
struct DataType< ::heron_srvs::GpsMission > {
  static const char* value()
  {
    return "heron_srvs/GpsMission";
  }

  static const char* value(const ::heron_srvs::GpsMission&) { return value(); }
};


// service_traits::MD5Sum< ::heron_srvs::GpsMissionRequest> should match
// service_traits::MD5Sum< ::heron_srvs::GpsMission >
template<>
struct MD5Sum< ::heron_srvs::GpsMissionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::GpsMission >::value();
  }
  static const char* value(const ::heron_srvs::GpsMissionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::GpsMissionRequest> should match
// service_traits::DataType< ::heron_srvs::GpsMission >
template<>
struct DataType< ::heron_srvs::GpsMissionRequest>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::GpsMission >::value();
  }
  static const char* value(const ::heron_srvs::GpsMissionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::heron_srvs::GpsMissionResponse> should match
// service_traits::MD5Sum< ::heron_srvs::GpsMission >
template<>
struct MD5Sum< ::heron_srvs::GpsMissionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::heron_srvs::GpsMission >::value();
  }
  static const char* value(const ::heron_srvs::GpsMissionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::heron_srvs::GpsMissionResponse> should match
// service_traits::DataType< ::heron_srvs::GpsMission >
template<>
struct DataType< ::heron_srvs::GpsMissionResponse>
{
  static const char* value()
  {
    return DataType< ::heron_srvs::GpsMission >::value();
  }
  static const char* value(const ::heron_srvs::GpsMissionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERON_SRVS_MESSAGE_GPSMISSION_H
